[theme]
base = "dark"

primaryColor = "#16C6B2"

backgroundColor = "#0B1117"

secondaryBackgroundColor = "#151F2A"

textColor = "#F5F7FA"

font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
